// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4Q1peyuQ_YnZ8jdGYhHyupo_LbNczDJE',
    appId: '1:897719037338:web:3aa2a872f4e66a13895e23',
    messagingSenderId: '897719037338',
    projectId: 'papakejamanekegaane',
    authDomain: 'papakejamanekegaane.firebaseapp.com',
    databaseURL: 'https://papakejamanekegaane-default-rtdb.firebaseio.com',
    storageBucket: 'papakejamanekegaane.firebasestorage.app',
    measurementId: 'G-3RNDLH15S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGTTQpI4ReztUjjhmktywYor0qGzZeuvM',
    appId: '1:897719037338:android:1c7050e3383cd2e8895e23',
    messagingSenderId: '897719037338',
    projectId: 'papakejamanekegaane',
    databaseURL: 'https://papakejamanekegaane-default-rtdb.firebaseio.com',
    storageBucket: 'papakejamanekegaane.firebasestorage.app',
  );
}
